version: '3.10'

services:
  django_gunicorn:
    build: .
    image: django_gunicorn
    volumes:
      - .:/code
    ports:
      - "80:80"
  # nginx:
  #   build: ./nginx
  #   volumes:
  #   - .:/code
  #   ports:
  #   - "80:80"
  #   depends_on:
  #     - django_gunicorn
