version: '3'

volumes:
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: fake_backend_production
    volumes:
      - production_django_media:/app/fake_production_backend/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: fake_backend_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: fake_backend_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
