# Generated by Django 4.2.2 on 2023-06-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flutter_app', '0002_test_is_false_alter_test_is_true'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTest',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_false',
        ),
        migrations.AlterField(
            model_name='test',
            name='is_true',
            field=models.BooleanField(),
        ),
    ]
