# Generated by Django 4.2.2 on 2023-06-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flutter_app', '0003_delete_testtest_remove_test_is_false_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='For_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
