#!/bin/bash

python3 manage.py makemigrations
python3 manage.py migrate --fake
python3 manage.py collectstatic --noinput
gunicorn backend_project.wsgi:application --bind 0.0.0.0:5000 --workers 4 -k "gevent"
gunicorn --limit-request-line 0