# Generated by Django 4.2.2 on 2023-07-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=True)),
                ('message', models.CharField(default='no message', max_length=100)),
            ],
            options={
                'db_table': 'for_test',
                'managed': True,
            },
        ),
    ]
