name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: deploy
      uses: actions/checkout@v2
      with:
      host: ${{secrets.SSH_HOST}}
      key: ${{secrets.SSH}}
      username: ${{secrets.SSH_USERNAME}}
      
      script: |
        mkdir test
        cd test
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag test-image:$(date +%s)
